MAINTAINER Cyprien Ruffino <ruffino.cyprien@gmail.com>

RUN apt-get update && apt-get install -y \
    cmake \
    cpio \
    gcc \
    g++ \
    gfortran \
    wget \
    build-essential \
    kmod \
    git \
    wget \
    python3\
    liblapack-dev \
    libopenblas-dev \
    python3-dev \
    python3-pip \
    python3-nose \
    python3-numpy \
    python3-scipy \
    libhdf5-dev \
    python3-h5py \
    python3-yaml

# Install MKL
RUN cd ~/GitHub/r-with-intel-mkl/
RUN wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
RUN apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB

RUN sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
RUN apt-get update && sudo apt-get install -y intel-mkl-64bit

RUN pip3 install pandas \
    numpy \
    h5py \
    Pillow \
    scipy \
    sklearn \
    progressbar2 \
    Theano \
    keras==2.0.6
