FROM debian
MAINTAINER Cyprien Ruffino <ruffino.cyprien@gmail.com>

RUN apt-get update && apt-get install -y \
    cmake \
    cpio \
    gcc \
    g++ \
    gfortran \
    wget \
    build-essential \
    kmod \
    git \
    wget \
    python3\
    liblapack-dev \
    libopenblas-dev \
    python3-dev \
    python3-pip \
    python3-nose \
    python3-numpy \
    python3-scipy \
    libhdf5-dev \
    python3-h5py \
    python3-yaml

RUN pip3 install pandas \
    numpy \
    h5py \
    Pillow \
    scipy \
    sklearn \
    progressbar2 \
    Theano \
    keras==2.0.6

RUN mkdir /root/.keras && \
    echo '{ \n\
    "image_data_format": "channels_last",\n\
    "floatx": "float32",\n\
    "backend": "theano",\n\
    "epsilon": 1e-07\n\
    }' > /root/.keras/keras.json

RUN pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
