from applications import classical_sgan_gen
from applications import classical_sgan_disc
from applications import conditional_disc
from applications import conditional_dilation_only_gen
from applications import conditional_upscaling_dilation_gen_mse
from applications import dilation_only_gen
from applications import upscaling_dilation_gen